<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_6CZHoN_wEeuQRohrGBPGsA" name="CopyPropositionHistoryToLyre" version="2.0" author="A1342495" bonitaVersion="7.14.6" bonitaModelVersion="7.12.0-004" configId="ACED000574002C436F707950726F706F736974696F6E486973746F7279546F4C797265372E382E332D303031372E382E347370">
    <elements xmi:type="process:Pool" xmi:id="_6CZHod_wEeuQRohrGBPGsA" name="CopyPropositionHistoryToLyre" version="2.0">
      <elements xmi:type="process:Lane" xmi:id="_6CZHot_wEeuQRohrGBPGsA" name="SMART" actor="_6CZIHN_wEeuQRohrGBPGsA">
        <elements xmi:type="process:StartEvent" xmi:id="_6CZHo9_wEeuQRohrGBPGsA" name="Start1" outgoing="_6CZID9_wEeuQRohrGBPGsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZHpN_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZHpd_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6CZHpt_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_6CZHp9_wEeuQRohrGBPGsA" documentation="Process To Call depends on variable &quot;statusMacroEtapes&quot; " name="Proposition Process" outgoing="_6CZIFd_wEeuQRohrGBPGsA" incoming="_6CZIEt_wEeuQRohrGBPGsA" type="SEQUENTIAL" collectionDataToMultiInstantiate="_6CZH4d_wEeuQRohrGBPGsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZHqN_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZHqd_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6CZHqt_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6CZHq9_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6CZHrN_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6CZHrd_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6CZHrt_wEeuQRohrGBPGsA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.sgdbf.model.Proposition" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6CZHr9_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_6CZHsN_wEeuQRohrGBPGsA" subprocessTarget="currentProposition" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_6CZHsd_wEeuQRohrGBPGsA" name="multiInstanceIterator" content="multiInstanceIterator" type="TYPE_VARIABLE" returnType="com.sgdbf.model.Proposition">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6CZHst_wEeuQRohrGBPGsA" name="multiInstanceIterator" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition"/>
            </processSource>
          </inputMappings>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_6CZHs9_wEeuQRohrGBPGsA" subprocessTarget="propositions" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_6CZHtN_wEeuQRohrGBPGsA" name="setListProposition" content="def list =[];&#xD;&#xA;list.add(multiInstanceIterator);&#xD;&#xA;return list;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6CZHtd_wEeuQRohrGBPGsA" name="multiInstanceIterator" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition"/>
            </processSource>
          </inputMappings>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_6CZHtt_wEeuQRohrGBPGsA" subprocessTarget="idInitiator" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_6CZHt9_wEeuQRohrGBPGsA" name="idInitiator" content="idInitiator" type="TYPE_VARIABLE" returnType="java.lang.Long">
              <referencedElements xmi:type="process:Data" xmi:id="_6CZHuN_wEeuQRohrGBPGsA" name="idInitiator" dataType="_6CZJ3t_wEeuQRohrGBPGsA"/>
            </processSource>
          </inputMappings>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_6CZHud_wEeuQRohrGBPGsA" subprocessTarget="urlWsdlLyre" assignationType="Data">
            <processSource xmi:type="expression:Expression" xmi:id="_6CZHut_wEeuQRohrGBPGsA" name="urlWSDLLyre" content="urlWSDLLyre" type="TYPE_PARAMETER">
              <referencedElements xmi:type="parameter:Parameter" xmi:id="_6CZHu9_wEeuQRohrGBPGsA" name="urlWSDLLyre" typeClassname="java.lang.String"/>
            </processSource>
          </inputMappings>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_6CZHvN_wEeuQRohrGBPGsA" subprocessSource="persistenceId" processTarget="_6CZIBd_wEeuQRohrGBPGsA"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_6CZHvd_wEeuQRohrGBPGsA" subprocessSource="caseId" processTarget="_6CZIB9_wEeuQRohrGBPGsA"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_6CZHvt_wEeuQRohrGBPGsA" name="CopyPropositionHistoryToLyreWorker" content="CopyPropositionHistoryToLyreWorker" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_6CZHv9_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_6CZHwN_wEeuQRohrGBPGsA" name="End1" incoming="_6CZIGN_wEeuQRohrGBPGsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZHwd_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZHwt_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6CZHw9_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_6CZHxN_wEeuQRohrGBPGsA" name="get propositions list" outgoing="_6CZIEt_wEeuQRohrGBPGsA" incoming="_6CZID9_wEeuQRohrGBPGsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZHxd_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZHxt_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6CZHx9_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_6CZHyN_wEeuQRohrGBPGsA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6CZHyd_wEeuQRohrGBPGsA" name="proposition" content="proposition" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6CZHyt_wEeuQRohrGBPGsA" name="proposition" multiple="true" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6CZHy9_wEeuQRohrGBPGsA" name="Proposition.find" content="SELECT p&#xA;FROM Proposition p&#xA;ORDER BY p.persistenceId" type="TYPE_QUERY_BUSINESS_DATA" returnType="java.util.List">
              <referencedElements xmi:type="expression:Expression" xmi:id="_6CZHzN_wEeuQRohrGBPGsA" name="startIndex" content="startIndex" type="QUERY_PARAM_TYPE" returnType="java.lang.Integer" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_6CZHzd_wEeuQRohrGBPGsA" name="0" content="0" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </referencedElements>
              <referencedElements xmi:type="expression:Expression" xmi:id="_6CZHzt_wEeuQRohrGBPGsA" name="maxResults" content="maxResults" type="QUERY_PARAM_TYPE" returnType="java.lang.Integer" returnTypeFixed="true">
                <referencedElements xmi:type="expression:Expression" xmi:id="_6CZHz9_wEeuQRohrGBPGsA" name="20000" content="20000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6CZH0N_wEeuQRohrGBPGsA" type="CREATE_BUSINESS_DATA"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_6CZH0d_wEeuQRohrGBPGsA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6CZH0t_wEeuQRohrGBPGsA" name="idInitiator" content="idInitiator" type="TYPE_VARIABLE" returnType="java.lang.Long">
              <referencedElements xmi:type="process:Data" xmi:id="_6CZH09_wEeuQRohrGBPGsA" name="idInitiator" dataType="_6CZJ3t_wEeuQRohrGBPGsA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6CZH1N_wEeuQRohrGBPGsA" name="setInit" content="return Long.parseLong(initiatorId);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long">
              <referencedElements xmi:type="parameter:Parameter" xmi:id="_6CZH1d_wEeuQRohrGBPGsA" name="initiatorId" typeClassname="java.lang.String"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6CZH1t_wEeuQRohrGBPGsA" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6CZH19_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6CZH2N_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6CZH2d_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6CZH2t_wEeuQRohrGBPGsA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6CZH29_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_6CZH3N_wEeuQRohrGBPGsA" name="Timer1" outgoing="_6CZIGN_wEeuQRohrGBPGsA" incoming="_6CZIFd_wEeuQRohrGBPGsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZH3d_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZH3t_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6CZH39_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_6CZH4N_wEeuQRohrGBPGsA" name="01:00:00" content="3600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_6CZH4d_wEeuQRohrGBPGsA" name="proposition" multiple="true" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH4t_wEeuQRohrGBPGsA" name="" content="" interpreter="GROOVY"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH49_wEeuQRohrGBPGsA" name="bonita_server_tenant" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH5N_wEeuQRohrGBPGsA" name="1" content="1"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH5d_wEeuQRohrGBPGsA" name="smtp_host" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH5t_wEeuQRohrGBPGsA" name="smtpauth.mail.saint-gobain.net" content="smtpauth.mail.saint-gobain.net"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH59_wEeuQRohrGBPGsA" name="noReplyMail" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH6N_wEeuQRohrGBPGsA" name="noreply-POPB@saint-gobain.com" content="noreply-POPB@saint-gobain.com"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH6d_wEeuQRohrGBPGsA" name="isDev" dataType="_6CZJ29_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH6t_wEeuQRohrGBPGsA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH69_wEeuQRohrGBPGsA" name="bonita_server_host" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH7N_wEeuQRohrGBPGsA" name="bpm.saint-gobain.com" content="bpm.saint-gobain.com"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH7d_wEeuQRohrGBPGsA" name="smtp_port" dataType="_6CZJ3d_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH7t_wEeuQRohrGBPGsA" name="25" content="25" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH79_wEeuQRohrGBPGsA" name="pop3_app" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH8N_wEeuQRohrGBPGsA" name="pop3p" content="pop3p"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH8d_wEeuQRohrGBPGsA" name="test" dataType="_6CZJ29_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH8t_wEeuQRohrGBPGsA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH89_wEeuQRohrGBPGsA" name="bonita_server_port" dataType="_6CZJ3d_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH9N_wEeuQRohrGBPGsA" name="443" content="443" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH9d_wEeuQRohrGBPGsA" name="smtp_userpassword" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH9t_wEeuQRohrGBPGsA" name="p/b23.NE" content="p/b23.NE"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH99_wEeuQRohrGBPGsA" name="smtp_username" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH-N_wEeuQRohrGBPGsA" name="CFRsvc-smtp-POPB" content="CFRsvc-smtp-POPB"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH-d_wEeuQRohrGBPGsA" name="nbrPropositionList" dataType="_6CZJ3d_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH-t_wEeuQRohrGBPGsA" content="" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH-9_wEeuQRohrGBPGsA" name="caseIdToUpdate" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH_N_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH_d_wEeuQRohrGBPGsA" name="urlWsdlLyre" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZH_t_wEeuQRohrGBPGsA" name="http://10.155.42.77:8080/Locprobin/Locpro.dll/WSDL?Module=BUDGEPOP" content="http://10.155.42.77:8080/Locprobin/Locpro.dll/WSDL?Module=BUDGEPOP"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZH_9_wEeuQRohrGBPGsA" name="smarteInitiatorId" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZIAN_wEeuQRohrGBPGsA" name="428" content="428" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_6CZIAd_wEeuQRohrGBPGsA" name="listIds" dataType="_6CZJ4d_wEeuQRohrGBPGsA" className="java.util.List">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZIAt_wEeuQRohrGBPGsA" name="init_listIds()" content="return new ArrayList();" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_6CZIA9_wEeuQRohrGBPGsA" name="listCaseIds" dataType="_6CZJ4d_wEeuQRohrGBPGsA" className="java.util.List">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZIBN_wEeuQRohrGBPGsA" name="init_listCaseIds()" content="return new ArrayList();" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZIBd_wEeuQRohrGBPGsA" name="propositionId" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZIBt_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZIB9_wEeuQRohrGBPGsA" name="caseId" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZICN_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZICd_wEeuQRohrGBPGsA" name="idInitiator" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZICt_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_6CZIC9_wEeuQRohrGBPGsA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_6CZIDN_wEeuQRohrGBPGsA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_6CZIDd_wEeuQRohrGBPGsA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_6CZIDt_wEeuQRohrGBPGsA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZID9_wEeuQRohrGBPGsA" target="_6CZHxN_wEeuQRohrGBPGsA" source="_6CZHo9_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZIEN_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZIEd_wEeuQRohrGBPGsA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZIEt_wEeuQRohrGBPGsA" target="_6CZHp9_wEeuQRohrGBPGsA" source="_6CZHxN_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZIE9_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZIFN_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZIFd_wEeuQRohrGBPGsA" target="_6CZH3N_wEeuQRohrGBPGsA" source="_6CZHp9_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZIFt_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZIF9_wEeuQRohrGBPGsA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZIGN_wEeuQRohrGBPGsA" target="_6CZHwN_wEeuQRohrGBPGsA" source="_6CZH3N_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZIGd_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZIGt_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_6CZIG9_wEeuQRohrGBPGsA" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_6CZIHN_wEeuQRohrGBPGsA" name="SMART"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_6CZIHd_wEeuQRohrGBPGsA" name="sgdbf-uat" version="7.12.0-004" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_6CZIHt_wEeuQRohrGBPGsA">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_6CZIH9_wEeuQRohrGBPGsA" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_6CZIIN_wEeuQRohrGBPGsA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_6CZIId_wEeuQRohrGBPGsA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_6CZIIt_wEeuQRohrGBPGsA"/>
            <users xmi:type="actormapping:Users" xmi:id="_6CZII9_wEeuQRohrGBPGsA"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_6CZIJN_wEeuQRohrGBPGsA" name="SMART">
            <groups xmi:type="actormapping:Groups" xmi:id="_6CZIJd_wEeuQRohrGBPGsA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_6CZIJt_wEeuQRohrGBPGsA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_6CZIJ9_wEeuQRohrGBPGsA"/>
            <users xmi:type="actormapping:Users" xmi:id="_6CZIKN_wEeuQRohrGBPGsA"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIKd_wEeuQRohrGBPGsA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIKt_wEeuQRohrGBPGsA" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIK9_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZILN_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZILd_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZILt_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIL9_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIMN_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIMd_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIMt_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIM9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZINN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZINd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZINt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIN9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZION_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIOd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIOt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIO9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIPN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagMG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagMW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagMm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagM2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagNG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagNW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagNm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagN2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIPd_wEeuQRohrGBPGsA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIPt_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIP9_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIQN_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIQd_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIQt_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIQ9_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIRN_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIRd_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIRt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIR9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZISN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZISd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZISt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIS9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZITN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZITd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZITt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIT9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagOG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagOW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagOm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagO2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagPG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagPW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagPm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XagP2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIUN_wEeuQRohrGBPGsA" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIUd_wEeuQRohrGBPGsA" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIUt_wEeuQRohrGBPGsA" name="urlWSDLLyre" value="https://lyre.dev.sgdbf.saint-gobain.net/Alocproweb/Locprobin/Locpro.dll/WSDL?Module=BUDGEPOP" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIU9_wEeuQRohrGBPGsA" name="initiatorId" value="1" typeClassname="java.lang.String"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_6CZIVN_wEeuQRohrGBPGsA" name="sgdbf-prod" version="7.12.0-004" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_6CZIVd_wEeuQRohrGBPGsA">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_6CZIVt_wEeuQRohrGBPGsA" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_6CZIV9_wEeuQRohrGBPGsA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_6CZIWN_wEeuQRohrGBPGsA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_6CZIWd_wEeuQRohrGBPGsA"/>
            <users xmi:type="actormapping:Users" xmi:id="_6CZIWt_wEeuQRohrGBPGsA"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_6CZIW9_wEeuQRohrGBPGsA" name="SMART">
            <groups xmi:type="actormapping:Groups" xmi:id="_6CZIXN_wEeuQRohrGBPGsA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_6CZIXd_wEeuQRohrGBPGsA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_6CZIXt_wEeuQRohrGBPGsA"/>
            <users xmi:type="actormapping:Users" xmi:id="_6CZIX9_wEeuQRohrGBPGsA"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIYN_wEeuQRohrGBPGsA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIYd_wEeuQRohrGBPGsA" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIYt_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIY9_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIZN_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIZd_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIZt_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIZ9_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIaN_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIad_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIat_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIa9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIbN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIbd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIbt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIb9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIcN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIcd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIct_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIc9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm0G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm0W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm0m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm02-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm1G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm1W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm1m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm12-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIdN_wEeuQRohrGBPGsA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIdd_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIdt_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZId9_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIeN_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIed_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIet_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIe9_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIfN_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIfd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIft_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIf9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIgN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIgd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIgt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIg9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIhN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIhd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIht_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm2G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm2W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm2m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm22-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm3G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm3W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm3m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xgm32-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIh9_wEeuQRohrGBPGsA" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIiN_wEeuQRohrGBPGsA" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIid_wEeuQRohrGBPGsA" name="urlWSDLLyre" value="https://lyre.prd.sgdbf.saint-gobain.net/alocproweb/locprobin/locpro.dll/wsdl?module=BUDGEPOP" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIit_wEeuQRohrGBPGsA" name="initiatorId" value="1" typeClassname="java.lang.String"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_6CZIi9_wEeuQRohrGBPGsA" name="Production" version="7.12.0-004" username="walter.bates" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_6CZIjN_wEeuQRohrGBPGsA">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_6CZIjd_wEeuQRohrGBPGsA" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_6CZIjt_wEeuQRohrGBPGsA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_6CZIj9_wEeuQRohrGBPGsA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_6CZIkN_wEeuQRohrGBPGsA"/>
            <users xmi:type="actormapping:Users" xmi:id="_6CZIkd_wEeuQRohrGBPGsA"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_6CZIkt_wEeuQRohrGBPGsA" name="SMART">
            <groups xmi:type="actormapping:Groups" xmi:id="_6CZIk9_wEeuQRohrGBPGsA"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_6CZIlN_wEeuQRohrGBPGsA"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_6CZIld_wEeuQRohrGBPGsA"/>
            <users xmi:type="actormapping:Users" xmi:id="_6CZIlt_wEeuQRohrGBPGsA"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIl9_wEeuQRohrGBPGsA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZImN_wEeuQRohrGBPGsA" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZImd_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZImt_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIm9_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZInN_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZInd_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZInt_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIn9_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIoN_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIod_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIot_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIo9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIpN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIpd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIpt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIp9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIqN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIqd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIqt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmtcG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmtcW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtcm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtc2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmtdG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmtdW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtdm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtd2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIq9_wEeuQRohrGBPGsA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIrN_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIrd_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIrt_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIr9_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIsN_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIsd_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIst_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIs9_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZItN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZItd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZItt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIt9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIuN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIud_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIut_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIu9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIvN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZIvd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmteG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmteW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtem-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmte2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmtfG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-XmtfW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtfm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-Xmtf2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZIvt_wEeuQRohrGBPGsA" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIv9_wEeuQRohrGBPGsA" name="urlWSDLLyre" typeClassname="java.lang.String"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIwN_wEeuQRohrGBPGsA" name="initiatorId" typeClassname="java.lang.String"/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIwd_wEeuQRohrGBPGsA" name="urlWSDLLyre" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_6CZIwt_wEeuQRohrGBPGsA" name="initiatorId" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_6CZIw9_wEeuQRohrGBPGsA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZIxN_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZIxd_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZIxt_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZIx9_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZIyN_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZIyd_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZIyt_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZIy9_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZIzN_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZIzd_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZIzt_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZIz9_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZI0N_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZI0d_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZI0t_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_6CZI09_wEeuQRohrGBPGsA" name="CopyPropositionHistoryToLyreWorker" version="2.0">
      <elements xmi:type="process:StartEvent" xmi:id="_6CZI1N_wEeuQRohrGBPGsA" name="Start2" outgoing="_6CZJLt_wEeuQRohrGBPGsA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZI1d_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZI1t_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_6CZI19_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_6CZI2N_wEeuQRohrGBPGsA" name="End" incoming="_6CZJNN_wEeuQRohrGBPGsA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZI2d_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZI2t_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_6CZI29_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_6CZI3N_wEeuQRohrGBPGsA" name="getTimeLines" outgoing="_6CZJMd_wEeuQRohrGBPGsA" incoming="_6CZJLt_wEeuQRohrGBPGsA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZI3d_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZI3t_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_6CZI39_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_6CZI4N_wEeuQRohrGBPGsA">
          <leftOperand xmi:type="expression:Expression" xmi:id="_6CZI4d_wEeuQRohrGBPGsA" name="currentTimeLines" content="currentTimeLines" type="TYPE_VARIABLE" returnType="java.util.List">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6CZI4t_wEeuQRohrGBPGsA" name="currentTimeLines" multiple="true" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.TimeLine"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_6CZI49_wEeuQRohrGBPGsA" name="currentProposition - Proposition#getTimeLines" content="currentProposition.getTimeLines()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6CZI5N_wEeuQRohrGBPGsA" name="currentProposition" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_6CZI5d_wEeuQRohrGBPGsA" type="CREATE_BUSINESS_DATA"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_6CZI5t_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_6CZI59_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6CZI6N_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_6CZI6d_wEeuQRohrGBPGsA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_6CZI6t_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_6CZI69_wEeuQRohrGBPGsA" name="Save to LYRE" outgoing="_6CZJNN_wEeuQRohrGBPGsA" incoming="_6CZJMd_wEeuQRohrGBPGsA" collectionDataToMultiInstantiate="_6CZJKN_wEeuQRohrGBPGsA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_6CZI7N_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_6CZI7d_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_6CZI7t_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <connectors xmi:type="process:Connector" xmi:id="_6CZI79_wEeuQRohrGBPGsA" name="saveToLYREBatch" definitionId="SaveHistoryToLYREBATCH" event="ON_FINISH" definitionVersion="1.1.1">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_6CZI8N_wEeuQRohrGBPGsA" definitionId="SaveHistoryToLYREBATCH" version="1.1.1" modelVersion="7.8.3-001">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6CZI8d_wEeuQRohrGBPGsA" key="cookie">
              <expression xmi:type="expression:Expression" xmi:id="_6CZI8t_wEeuQRohrGBPGsA" name="cookie()" content="return &quot;webservice&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6CZI89_wEeuQRohrGBPGsA" key="urlWSDL">
              <expression xmi:type="expression:Expression" xmi:id="_6CZI9N_wEeuQRohrGBPGsA" name="urlWsdlLyre" content="urlWsdlLyre" type="TYPE_VARIABLE" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_6CZI9d_wEeuQRohrGBPGsA" name="urlWsdlLyre" dataType="_6CZJ4N_wEeuQRohrGBPGsA"/>
              </expression>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6CZI9t_wEeuQRohrGBPGsA" key="currentProposition">
              <expression xmi:type="expression:Expression" xmi:id="_6CZI99_wEeuQRohrGBPGsA" name="currentProposition" content="currentProposition" type="TYPE_VARIABLE" returnType="com.sgdbf.model.Proposition" returnTypeFixed="true">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6CZI-N_wEeuQRohrGBPGsA" name="currentProposition" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition"/>
              </expression>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_6CZI-d_wEeuQRohrGBPGsA" key="currentTimeLine">
              <expression xmi:type="expression:Expression" xmi:id="_6CZI-t_wEeuQRohrGBPGsA" name="" content="" returnType="com.sgdbf.model.TimeLine" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </connectors>
        <loopCondition xmi:type="expression:Expression" xmi:id="_6CZI-9_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_6CZI_N_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6CZI_d_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_6CZI_t_wEeuQRohrGBPGsA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.sgdbf.model.TimeLine" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_6CZI_9_wEeuQRohrGBPGsA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_6CZJAN_wEeuQRohrGBPGsA" name="currentProposition" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJAd_wEeuQRohrGBPGsA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_6CZJAt_wEeuQRohrGBPGsA" name="propositions" multiple="true" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.Proposition">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJA9_wEeuQRohrGBPGsA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJBN_wEeuQRohrGBPGsA" name="bonita_server_host" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJBd_wEeuQRohrGBPGsA" name="bpm.saint-gobain.com" content="bpm.saint-gobain.com"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJBt_wEeuQRohrGBPGsA" name="bonita_server_port" dataType="_6CZJ3d_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJB9_wEeuQRohrGBPGsA" name="443" content="443" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJCN_wEeuQRohrGBPGsA" name="bonita_server_tenant" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJCd_wEeuQRohrGBPGsA" name="1" content="1"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJCt_wEeuQRohrGBPGsA" name="smtp_host" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJC9_wEeuQRohrGBPGsA" name="smtpauth.mail.saint-gobain.net" content="smtpauth.mail.saint-gobain.net"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJDN_wEeuQRohrGBPGsA" name="noReplyMail" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJDd_wEeuQRohrGBPGsA" name="noreply-POPB@saint-gobain.com" content="noreply-POPB@saint-gobain.com"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJDt_wEeuQRohrGBPGsA" name="isDev" dataType="_6CZJ29_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJD9_wEeuQRohrGBPGsA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJEN_wEeuQRohrGBPGsA" name="smtp_port" dataType="_6CZJ3d_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJEd_wEeuQRohrGBPGsA" name="25" content="25" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJEt_wEeuQRohrGBPGsA" name="pop3_app" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJE9_wEeuQRohrGBPGsA" name="pop3p" content="pop3p"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJFN_wEeuQRohrGBPGsA" name="test" dataType="_6CZJ29_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJFd_wEeuQRohrGBPGsA" name="true" content="true" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJFt_wEeuQRohrGBPGsA" name="smtp_userpassword" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJF9_wEeuQRohrGBPGsA" name="p/b23.NE" content="p/b23.NE"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJGN_wEeuQRohrGBPGsA" name="smtp_username" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJGd_wEeuQRohrGBPGsA" name="CFRsvc-smtp-POPB" content="CFRsvc-smtp-POPB"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJGt_wEeuQRohrGBPGsA" name="smarteInitiatorId" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJG9_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJHN_wEeuQRohrGBPGsA" name="nbrPropositionList" dataType="_6CZJ3d_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJHd_wEeuQRohrGBPGsA" content="" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJHt_wEeuQRohrGBPGsA" name="urlWsdlLyre" dataType="_6CZJ4N_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJH9_wEeuQRohrGBPGsA" content=""/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_6CZJIN_wEeuQRohrGBPGsA" name="hierarchyList" dataType="_6CZJ4d_wEeuQRohrGBPGsA" className="java.util.List">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJId_wEeuQRohrGBPGsA" content="" returnType="java.util.List"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJIt_wEeuQRohrGBPGsA" name="persistenceId" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJI9_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJJN_wEeuQRohrGBPGsA" name="caseId" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJJd_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_6CZJJt_wEeuQRohrGBPGsA" name="idInitiator" dataType="_6CZJ3t_wEeuQRohrGBPGsA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJJ9_wEeuQRohrGBPGsA" content="" returnType="java.lang.Long"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_6CZJKN_wEeuQRohrGBPGsA" name="currentTimeLines" multiple="true" dataType="_6CZJ49_wEeuQRohrGBPGsA" className="com.sgdbf.model.TimeLine">
        <defaultValue xmi:type="expression:Expression" xmi:id="_6CZJKd_wEeuQRohrGBPGsA" name="" content="" interpreter="GROOVY"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_6CZJKt_wEeuQRohrGBPGsA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_6CZJK9_wEeuQRohrGBPGsA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_6CZJLN_wEeuQRohrGBPGsA" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_6CZJLd_wEeuQRohrGBPGsA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZJLt_wEeuQRohrGBPGsA" target="_6CZI3N_wEeuQRohrGBPGsA" source="_6CZI1N_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZJL9_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZJMN_wEeuQRohrGBPGsA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZJMd_wEeuQRohrGBPGsA" target="_6CZI69_wEeuQRohrGBPGsA" source="_6CZI3N_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZJMt_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZJM9_wEeuQRohrGBPGsA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6CZJNN_wEeuQRohrGBPGsA" target="_6CZI2N_wEeuQRohrGBPGsA" source="_6CZI69_wEeuQRohrGBPGsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6CZJNd_wEeuQRohrGBPGsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6CZJNt_wEeuQRohrGBPGsA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <configurations xmi:type="configuration:Configuration" xmi:id="_6CZJN9_wEeuQRohrGBPGsA" name="sgdbf-prod" version="7.12.0-004" username="walter.bates" password="bpm">
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_6CZJON_wEeuQRohrGBPGsA" type="CONNECTOR" definitionId="SaveHistoryToLYREBATCH" definitionVersion="1.1.1" implementationId="SaveHistoryToLYREBATCH-impl" implementationVersion="1.1.1"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJOd_wEeuQRohrGBPGsA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJOt_wEeuQRohrGBPGsA" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_6CZJO9_wEeuQRohrGBPGsA" id="SaveHistoryToLYREBATCH-impl-1.1.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJPN_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="SaveHistoryToLYREBATCH-impl-1.1.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJPd_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="jsoup-1.12.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJPt_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="LyreWebServices-2.3.0.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJP9_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJQN_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJQd_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJQt_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJQ9_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJRN_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJRd_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJRt_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJR9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJSN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJSd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJSt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJS9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJTN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJTd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJTt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJT9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJUN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-beg0G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-beg0W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu8G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu8W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu8m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu82-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu9G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu9W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJUd_wEeuQRohrGBPGsA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJUt_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJU9_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJVN_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJVd_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJVt_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJV9_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJWN_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJWd_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJWt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJW9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJXN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJXd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJXt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJX9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJYN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJYd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJYt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJY9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu9m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu92-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu-G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu-W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu-m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu-2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu_G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-bfu_W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJZN_wEeuQRohrGBPGsA" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJZd_wEeuQRohrGBPGsA" id="OTHER"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_6CZJZt_wEeuQRohrGBPGsA" name="sgdbf-uat" version="7.12.0-004" username="walter.bates" password="bpm">
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_6CZJZ9_wEeuQRohrGBPGsA" type="CONNECTOR" definitionId="SaveHistoryToLYREBATCH" definitionVersion="1.1.1" implementationId="SaveHistoryToLYREBATCH-impl" implementationVersion="1.1.1"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJaN_wEeuQRohrGBPGsA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJad_wEeuQRohrGBPGsA" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_6CZJat_wEeuQRohrGBPGsA" id="SaveHistoryToLYREBATCH-impl-1.1.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJa9_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="SaveHistoryToLYREBATCH-impl-1.1.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJbN_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="jsoup-1.12.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJbd_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="LyreWebServices-2.3.0.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJbt_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJb9_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJcN_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJcd_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJct_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJc9_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJdN_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJdd_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJdt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJd9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJeN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJed_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJet_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJe9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJfN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJfd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJft_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJf9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp0G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp0W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp0m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp02-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp1G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp1W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp1m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp12-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJgN_wEeuQRohrGBPGsA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJgd_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJgt_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJg9_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJhN_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJhd_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJht_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJh9_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJiN_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJid_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJit_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJi9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJjN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJjd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJjt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJj9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJkN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJkd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJkt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp2G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp2W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp2m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp22-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp3G-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp3W-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp3m-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-fSp32-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJk9_wEeuQRohrGBPGsA" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJlN_wEeuQRohrGBPGsA" id="OTHER"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_6CZJld_wEeuQRohrGBPGsA" name="Production" version="7.12.0-004" username="walter.bates" password="bpm">
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_6CZJlt_wEeuQRohrGBPGsA" type="CONNECTOR" definitionId="SaveHistoryToLYREBATCH" definitionVersion="1.1.1" implementationId="SaveHistoryToLYREBATCH-impl" implementationVersion="1.1.1"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJl9_wEeuQRohrGBPGsA" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJmN_wEeuQRohrGBPGsA" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_6CZJmd_wEeuQRohrGBPGsA" id="SaveHistoryToLYREBATCH-impl-1.1.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJmt_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="SaveHistoryToLYREBATCH-impl-1.1.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJm9_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="jsoup-1.12.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJnN_wEeuQRohrGBPGsA" key="SaveHistoryToLYREBATCH-impl -- 1.1.1" value="LyreWebServices-2.3.0.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJnd_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJnt_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJn9_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJoN_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJod_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJot_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJo9_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJpN_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJpd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJpt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJp9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJqN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJqd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJqt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJq9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJrN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJrd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJrt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzAG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzAW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzAm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzA2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzBG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzBW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzBm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzB2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJr9_wEeuQRohrGBPGsA" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJsN_wEeuQRohrGBPGsA" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJsd_wEeuQRohrGBPGsA" id="GROOVY_SCRIPT">
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJst_wEeuQRohrGBPGsA" key="ConfigFile.groovy" value="ConfigFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJs9_wEeuQRohrGBPGsA" key="MailContent.groovy" value="MailContent.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJtN_wEeuQRohrGBPGsA" key="MailTemplate.groovy" value="MailTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJtd_wEeuQRohrGBPGsA" key="PropositionTemplate.groovy" value="PropositionTemplate.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJtt_wEeuQRohrGBPGsA" key="TestScript.groovy" value="TestScript.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJt9_wEeuQRohrGBPGsA" key="UserDetails.groovy" value="UserDetails.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJuN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/ActivityState.groovy" value="com/sgdbf/pop3p/groovy/ActivityState.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJud_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" value="com/sgdbf/pop3p/groovy/AnalyzeWebServiceResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJut_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" value="com/sgdbf/pop3p/groovy/CheckConnectorExecution.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJu9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" value="com/sgdbf/pop3p/groovy/EnvironmentParameters.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJvN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LogFile.groovy" value="com/sgdbf/pop3p/groovy/LogFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJvd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" value="com/sgdbf/pop3p/groovy/LyrePreOrderCreationResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJvt_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUser.groovy" value="com/sgdbf/pop3p/groovy/LyreUser.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJv9_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" value="com/sgdbf/pop3p/groovy/LyreUserProfiles.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJwN_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" value="com/sgdbf/pop3p/groovy/LyreUsersResponse.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_6CZJwd_wEeuQRohrGBPGsA" key="com/sgdbf/pop3p/groovy/MailRecipient.groovy" value="com/sgdbf/pop3p/groovy/MailRecipient.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzCG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/BDMUtility.groovy" value="com/sgdbf/pop3p/groovy/BDMUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzCW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelData.groovy" value="com/sgdbf/pop3p/groovy/ExcelData.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzCm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ExcelFile.groovy" value="com/sgdbf/pop3p/groovy/ExcelFile.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzC2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FileUtility.groovy" value="com/sgdbf/pop3p/groovy/FileUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzDG-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" value="com/sgdbf/pop3p/groovy/FrenchBusinessDays.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzDW-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" value="com/sgdbf/pop3p/groovy/LocaleUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzDm-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/StringUtility.groovy" value="com/sgdbf/pop3p/groovy/StringUtility.groovy" exported="false" type="GROOVY_SCRIPT"/>
          <fragments xmi:type="configuration:Fragment" xmi:id="_-iXzD2-EEey7IpcoEkoV4w" key="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" value="com/sgdbf/pop3p/groovy/ValidationDueDateCalculation.groovy" exported="false" type="GROOVY_SCRIPT"/>
        </applicationDependencies>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_6CZJwt_wEeuQRohrGBPGsA" id="OTHER"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_6CZJw9_wEeuQRohrGBPGsA"/>
      <documents xmi:type="process:Document" xmi:id="_6CZJxN_wEeuQRohrGBPGsA" name="fileExcel" defaultValueIdOfDocumentStore="SONEN DIEPPE guisnel.xlsx" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_6CZJxd_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_6CZJxt_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_6CZJx9_wEeuQRohrGBPGsA" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="_6CZJyN_wEeuQRohrGBPGsA" name="fichierPdf" defaultValueIdOfDocumentStore="Etude X 158 BS3   Benne 5500 mm projet Normandie.pdf" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_6CZJyd_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_6CZJyt_wEeuQRohrGBPGsA" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_6CZJy9_wEeuQRohrGBPGsA" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZJzN_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZJzd_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZJzt_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZJz9_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZJ0N_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZJ0d_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZJ0t_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZJ09_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZJ1N_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZJ1d_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZJ1t_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZJ19_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_6CZJ2N_wEeuQRohrGBPGsA">
        <name xmi:type="expression:Expression" xmi:id="_6CZJ2d_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_6CZJ2t_wEeuQRohrGBPGsA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_6CZJ29_wEeuQRohrGBPGsA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_6CZJ3N_wEeuQRohrGBPGsA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_6CZJ3d_wEeuQRohrGBPGsA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_6CZJ3t_wEeuQRohrGBPGsA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_6CZJ39_wEeuQRohrGBPGsA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_6CZJ4N_wEeuQRohrGBPGsA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_6CZJ4d_wEeuQRohrGBPGsA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_6CZJ4t_wEeuQRohrGBPGsA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_6CZJ49_wEeuQRohrGBPGsA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_6CZJ5N_wEeuQRohrGBPGsA" type="Process" element="_6CZHoN_wEeuQRohrGBPGsA" name="MyDiagram6" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_6CZJ5d_wEeuQRohrGBPGsA" type="2007" element="_6CZHod_wEeuQRohrGBPGsA">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ5t_wEeuQRohrGBPGsA" type="5008" element="_6CZHod_wEeuQRohrGBPGsA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ59_wEeuQRohrGBPGsA" type="7001" element="_6CZHod_wEeuQRohrGBPGsA">
        <children xmi:type="notation:Node" xmi:id="_6CZJ6N_wEeuQRohrGBPGsA" type="3007" element="_6CZHot_wEeuQRohrGBPGsA">
          <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ6d_wEeuQRohrGBPGsA" type="5007" element="_6CZHot_wEeuQRohrGBPGsA"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ6t_wEeuQRohrGBPGsA" type="7002" element="_6CZHot_wEeuQRohrGBPGsA">
            <children xmi:type="notation:Shape" xmi:id="_6CZJ69_wEeuQRohrGBPGsA" type="3002" element="_6CZHo9_wEeuQRohrGBPGsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ7N_wEeuQRohrGBPGsA" type="5024" element="_6CZHo9_wEeuQRohrGBPGsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZJ7d_wEeuQRohrGBPGsA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZJ7t_wEeuQRohrGBPGsA" x="62" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6CZJ79_wEeuQRohrGBPGsA" type="3063" element="_6CZHp9_wEeuQRohrGBPGsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ8N_wEeuQRohrGBPGsA" type="5093" element="_6CZHp9_wEeuQRohrGBPGsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZJ8d_wEeuQRohrGBPGsA" x="499" y="87" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6CZJ8t_wEeuQRohrGBPGsA" type="3062" element="_6CZHwN_wEeuQRohrGBPGsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ89_wEeuQRohrGBPGsA" type="5090" element="_6CZHwN_wEeuQRohrGBPGsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZJ9N_wEeuQRohrGBPGsA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZJ9d_wEeuQRohrGBPGsA" x="965" y="114"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6CZJ9t_wEeuQRohrGBPGsA" type="3027" element="_6CZHxN_wEeuQRohrGBPGsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ99_wEeuQRohrGBPGsA" type="5017" element="_6CZHxN_wEeuQRohrGBPGsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZJ-N_wEeuQRohrGBPGsA" x="214" y="95" width="138" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6CZJ-d_wEeuQRohrGBPGsA" type="3017" element="_6CZH3N_wEeuQRohrGBPGsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6CZJ-t_wEeuQRohrGBPGsA" type="5032" element="_6CZH3N_wEeuQRohrGBPGsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZJ-9_wEeuQRohrGBPGsA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZJ_N_wEeuQRohrGBPGsA" x="784" y="110"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6CZJ_d_wEeuQRohrGBPGsA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6CZJ_t_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6CZJ_9_wEeuQRohrGBPGsA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6CZKAN_wEeuQRohrGBPGsA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKAd_wEeuQRohrGBPGsA"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_6CZKAt_wEeuQRohrGBPGsA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKA9_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_6CZKBN_wEeuQRohrGBPGsA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_6CZKBd_wEeuQRohrGBPGsA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKBt_wEeuQRohrGBPGsA" width="1126" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_6CZKB9_wEeuQRohrGBPGsA" type="2007" element="_6CZI09_wEeuQRohrGBPGsA">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKCN_wEeuQRohrGBPGsA" type="5008" element="_6CZI09_wEeuQRohrGBPGsA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKCd_wEeuQRohrGBPGsA" type="7001" element="_6CZI09_wEeuQRohrGBPGsA">
        <children xmi:type="notation:Shape" xmi:id="_6CZKCt_wEeuQRohrGBPGsA" type="3002" element="_6CZI1N_wEeuQRohrGBPGsA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_6CZKC9_wEeuQRohrGBPGsA" type="5024" element="_6CZI1N_wEeuQRohrGBPGsA">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKDN_wEeuQRohrGBPGsA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKDd_wEeuQRohrGBPGsA" x="84" y="98"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_6CZKDt_wEeuQRohrGBPGsA" type="3003" element="_6CZI2N_wEeuQRohrGBPGsA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_6CZKD9_wEeuQRohrGBPGsA" type="5025" element="_6CZI2N_wEeuQRohrGBPGsA">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKEN_wEeuQRohrGBPGsA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKEd_wEeuQRohrGBPGsA" x="1016" y="93" width="30" height="30"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_6CZKEt_wEeuQRohrGBPGsA" type="3027" element="_6CZI3N_wEeuQRohrGBPGsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_6CZKE9_wEeuQRohrGBPGsA" type="5017" element="_6CZI3N_wEeuQRohrGBPGsA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKFN_wEeuQRohrGBPGsA" x="317" y="78" width="139" height="69"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_6CZKFd_wEeuQRohrGBPGsA" type="3027" element="_6CZI69_wEeuQRohrGBPGsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_6CZKFt_wEeuQRohrGBPGsA" type="5017" element="_6CZI69_wEeuQRohrGBPGsA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKF9_wEeuQRohrGBPGsA" x="698" y="78" width="120" height="60"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_6CZKGN_wEeuQRohrGBPGsA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKGd_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_6CZKGt_wEeuQRohrGBPGsA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_6CZKG9_wEeuQRohrGBPGsA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6CZKHN_wEeuQRohrGBPGsA" width="1191" height="226"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_6CZKHd_wEeuQRohrGBPGsA"/>
    <edges xmi:type="notation:Connector" xmi:id="_6CZKHt_wEeuQRohrGBPGsA" type="4001" element="_6CZID9_wEeuQRohrGBPGsA" source="_6CZJ69_wEeuQRohrGBPGsA" target="_6CZJ9t_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKH9_wEeuQRohrGBPGsA" type="6001" element="_6CZID9_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKIN_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKId_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZKIt_wEeuQRohrGBPGsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6CZKI9_wEeuQRohrGBPGsA" type="4001" element="_6CZIEt_wEeuQRohrGBPGsA" source="_6CZJ9t_wEeuQRohrGBPGsA" target="_6CZJ79_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKJN_wEeuQRohrGBPGsA" type="6001" element="_6CZIEt_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKJd_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKJt_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZKJ9_wEeuQRohrGBPGsA" points="[0, -11, -163, -12]$[147, -11, -16, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZKKN_wEeuQRohrGBPGsA" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZKKd_wEeuQRohrGBPGsA" id="(0.10526315789473684,0.6447368421052632)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6CZKKt_wEeuQRohrGBPGsA" type="4001" element="_6CZIFd_wEeuQRohrGBPGsA" source="_6CZJ79_wEeuQRohrGBPGsA" target="_6CZJ-d_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKK9_wEeuQRohrGBPGsA" type="6001" element="_6CZIFd_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKLN_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKLd_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZKLt_wEeuQRohrGBPGsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6CZKL9_wEeuQRohrGBPGsA" type="4001" element="_6CZIGN_wEeuQRohrGBPGsA" source="_6CZJ-d_wEeuQRohrGBPGsA" target="_6CZJ8t_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKMN_wEeuQRohrGBPGsA" type="6001" element="_6CZIGN_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKMd_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKMt_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZKM9_wEeuQRohrGBPGsA" points="[-1, -17, -134, 13]$[130, -36, -3, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZKNN_wEeuQRohrGBPGsA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZKNd_wEeuQRohrGBPGsA" id="(0.36666666666666664,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6CZKNt_wEeuQRohrGBPGsA" type="4001" element="_6CZJLt_wEeuQRohrGBPGsA" source="_6CZKCt_wEeuQRohrGBPGsA" target="_6CZKEt_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKN9_wEeuQRohrGBPGsA" type="6001" element="_6CZJLt_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZKON_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZKOd_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZKOt_wEeuQRohrGBPGsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6CZKO9_wEeuQRohrGBPGsA" type="4001" element="_6CZJMd_wEeuQRohrGBPGsA" source="_6CZKEt_wEeuQRohrGBPGsA" target="_6CZKFd_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZKPN_wEeuQRohrGBPGsA" type="6001" element="_6CZJMd_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZusN_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZusd_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZust_wEeuQRohrGBPGsA" points="[0, 1, -248, 12]$[242, 1, -6, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZus9_wEeuQRohrGBPGsA" id="(1.0,0.4782608695652174)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZutN_wEeuQRohrGBPGsA" id="(0.05,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6CZutd_wEeuQRohrGBPGsA" type="4001" element="_6CZJNN_wEeuQRohrGBPGsA" source="_6CZKFd_wEeuQRohrGBPGsA" target="_6CZKDt_wEeuQRohrGBPGsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6CZutt_wEeuQRohrGBPGsA" type="6001" element="_6CZJNN_wEeuQRohrGBPGsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6CZut9_wEeuQRohrGBPGsA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6CZuuN_wEeuQRohrGBPGsA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6CZuud_wEeuQRohrGBPGsA" points="[0, 0, -201, 0]$[198, -1, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZuut_wEeuQRohrGBPGsA" id="(1.0,0.55)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6CZuu9_wEeuQRohrGBPGsA" id="(0.1,0.43333333333333335)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
